# バージョンの指定
version: "3.3"

# サービスの定義
services: 
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: end_year_tax_adjustment
      POSTGRES_PASSWORD: password
    ports: 
      - "5432:5432"
    volumes: 
      - database:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
            
  

volumes: 
  database:
    driver: local